spring:
  application:
    name: parking
  mail:
    host: smtp.gmail.com
    port: 587
    username: beastieapis@gmail.com
    password: mfpbmrqvmwyozwvn
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
#  need 32 char
  secret: YOUR-SECRET-HERE (32 CHAR)
  expiration: 86400000
